apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "databaseuser"
  DB_NAME: "guestbook"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"